### PR TITLE
Update to a more standard format

### PR DESCRIPTION
**Pull request by ColinEberhardt**
Just a few tweaks to make the markdown formatting to the other awesome lists

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
You can see it rendered here: https://github.com/ColinEberhardt/awesome-redux/tree/patch-1

**Comment by xgrommx** [comment]
@ColinEberhardt Why do u think that is a more better formatting?

**Comment by ColinEberhardt** [comment]
That's a very good question! - and the answer is a little biased ;-)

I've been writing a little bot that checks links and adds GitHub star counts to Awesome lists. I'm beta-testing it at the moment, and you can see its activity here:

http://colineberhardt.github.io/awesome-lists-bot/

This bot assumes that Awesome lists have a reasonably similar format, and I have found that around 95% all have the same format. 

So I think this is a better formatting because it is the one used by most lists ... and because I am biased and would like to use my bot to add star counts (if you are happy with this too)

**Comment by xgrommx** [comment]
I need to think about this one and then I'll to merge it. Thanks!

**Comment by ColinEberhardt** [comment]
No worries, thanks for considering this :-)

**Pull request closed without merging**
